 - id: snippet-fmt
   name: snippet-fmt
   entry: snippet-fmt
   language: python
   types_or: [python, pyi]
   require_serial: false
   args:
      - --verbose
      - --diff
   additional_dependencies: []
